# Generated by Django 5.1.1 on 2025-05-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-created_at'], 'verbose_name': 'Medical Practitioner', 'verbose_name_plural': 'Medical Practitioners'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Clinic Address'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(choices=[('nairobi', 'Nairobi'), ('mombasa', 'Mombasa'), ('kisumu', 'Kisumu'), ('nakuru', 'Nakuru'), ('eldoret', 'Eldoret'), ('thika', 'Thika'), ('naivasha', 'Naivasha')], default='nairobi', max_length=20, verbose_name='Practice City'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='occupation',
            field=models.CharField(choices=[('DR', 'Doctor'), ('NR', 'Nurse'), ('NEU', 'Neurologist'), ('CL', 'Clinical Officer'), ('PH', 'Pharmacist'), ('DT', 'Dentist')], default='DR', max_length=3, verbose_name='Medical Specialty'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/avatars/', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Professional Biography'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registration Date'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(help_text='Format: 2547XXXXXXXX', max_length=15, verbose_name='Phone Number'),
        ),
    ]
