# Generated by Django 5.1.1 on 2025-05-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0002_alter_doctor_options_doctor_address_doctor_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='county',
            field=models.CharField(blank=True, max_length=50, verbose_name='County'),
        ),
    ]
